baseURL = 'https://bohrm1.github.io/matthewbohr.github.io/'
languageCode = 'en-us'
title = "Matthew Bohr's Website"

theme = "coder-portfolio"

defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Matthew Bohr" # Author's name.
    info = "I am an electrical engineering major at The College of New Jersey and my expected graduation date is May 2023. I am looking for positions in embedded systems, hardware design, wireless technology, or antenna design" # Author's job title or info.
    description = "HMatthew Bohr's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "/website_photo.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
     #fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bohrm1"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/matthew-bohr-5a00661b8/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"